In [2]:
import numpy as np

### Creating array from list

In [3]:
# 1D array
arr_1d = np.array([1,2,3,4,5])
print(f"1D array : {arr_1d}")

arr_2d = np.array([[1,2] , [1,2]])
print(f"2D array : {arr_2d}")

1D array : [1 2 3 4 5]
2D array : [[1 2]
 [1 2]]


### List vs np array

In [4]:
l = [1,2,3]
arr = np.array([1,2,3])
arr1 = np.array([4,5,6])

print(f"normal list multiplication = {l * 2}")
print(f"numpy matrice list multiplication = {arr * 2}")
print(f"two matrices multiplication = {arr * arr1}")


normal list multiplication = [1, 2, 3, 1, 2, 3]
numpy matrice list multiplication = [2 4 6]
two matrices multiplication = [ 4 10 18]


In [5]:
# Multiplying n-dim matrices
# @ = Matrix multiplication
# * = normal element wise multiplication

arr2 = np.array([[1,2,3]])
arr3 = np.array([[4,5,6]])

print(f"noraml multiplication = {arr2 * arr3}")

arr2 = np.array([[1,2,3]])
arr3 = np.array([
        [4,5,6],
        [1,2,3],
        [7,8,9]
    ])

print(f"matrix multiplication = {arr2 @ arr3}")

noraml multiplication = [[ 4 10 18]]
matrix multiplication = [[27 33 39]]


### Creating matrices using numpy

In [6]:
zeros = np.zeros((2,2))
ones = np.ones((2,2))
full = np.full((2,2) , 69)

print(f"zeroes matrix = \n{zeros}")
print(f"ones matrix = \n{ones}")
print(f"full matrix = \n{full}")

zeroes matrix = 
[[0. 0.]
 [0. 0.]]
ones matrix = 
[[1. 1.]
 [1. 1.]]
full matrix = 
[[69 69]
 [69 69]]


In [15]:
# Random is a class in itself
# The major diff between these 2 is how you pass ur dim
random = np.random.random((2,2)) # takes tuple
rand = np.random.rand(2,2) # takes seperate value
randint = np.random.randint(1,100,(2,10))

print(f"random matrix = \n{random}")
print(f"rand matrix = \n{rand}")
print(f"randint matrix = \n{randint}")


random matrix = 
[[0.42525985 0.84954513]
 [0.20395674 0.06057066]]
rand matrix = 
[[0.22056249 0.53506149]
 [0.84865276 0.77071092]]
randint matrix = 
[[59 12 82 95 16 65 13  5 64  2]
 [64 47 24 29 23 30 24 65 86 13]]


### Vector , Matrix and Tensor

In [32]:
v = np.array([1,2,3])
m = np.array([[1,2] , [2,3]])

# Tensor = more than 2 dimension or multiple dimension
tensor = np.array(
    [
        [
            [1,2],
            [3,4]
        ] ,
        [
            [5,6],
            [7,8]
        ]
    ]
)

print(f"vector = \n{v}")
print(f"matrix = \n{m} of dim = {m.shape}")
print(f"Tensor = \n{tensor}")
# basic properties
print(f"Tensor shape = {tensor.shape}")
print(f"Tensor dimension = {tensor.ndim}")
print(f"Tensor size = {tensor.size}") # total no of elements inside the array
print(tensor[0])


vector = 
[1 2 3]
matrix = 
[[1 2]
 [2 3]] of dim = (2, 2)
Tensor = 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Tensor shape = (2, 2, 2)
Tensor dimension = 3
Tensor size = 8
[[1 2]
 [3 4]]


### Array Reshaping

In [44]:
a = np.arange(1,11)

# always remember that while reshaping dim u pass in the parameter ,
# their multiplication should be equal to the number of elements
# inside the array u r reshaping .
# Like here -> 2 * 5 = 10
reshape = a.reshape((2,5))
flattened = reshape.flatten()
transpose = reshape.T # rows to col and vice-versa

print(f"Reshaped array = \n{reshape}")
print(f"Flattened array = \n{flattened}")
print(f"Transposed array = \n{transpose}")

Reshaped array = 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Flattened array = 
[ 1  2  3  4  5  6  7  8  9 10]
Transposed array = 
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
