## Numpy Array Operations

In [2]:
import numpy as np

In [3]:
arr = np.arange(1,11)
print(arr)
arr_2d = arr.reshape((2,5))
print(arr_2d)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Slicing 2D-Array

In [4]:
# 3rd element of 1st row 
print(f"3rd element = {arr_2d[0][2]}")
print(f"3rd element = {arr_2d[0,2]}") # other way of writing the same thing

# all elements after 2nd one in 2nd row (excluding)
print(f"particular elements = {arr_2d[1][2:]}") 

# last element of last row 
print(f"last element of last row = {arr_2d[-1][-1]}")

# Only first column
print(f"First column = {arr_2d[:,1]}")

3rd element = 3
3rd element = 3
particular elements = [ 8  9 10]
last element of last row = 10
First column = [2 7]


### Sorting

In [5]:
arr_2d_unsorted = np.array([
    [1,2],
    [2,1] 
])
# axis = 0 -> brings smallest value in top row 
print(f"Sorted 2D array : \n{np.sort(arr_2d_unsorted , axis=0)}")

# axis = 1 -> brings smallest value in first col 
print(f"Sorted 2D array : \n{np.sort(arr_2d_unsorted , axis=1)}")

Sorted 2D array : 
[[1 1]
 [2 2]]
Sorted 2D array : 
[[1 2]
 [1 2]]


### Filtering

In [6]:
arr = np.arange(1,11)

even_no = arr[arr % 2 == 0]
print(f"Even numebers : {even_no}")

Even numebers : [ 2  4  6  8 10]


In [7]:
# Filter with mask
# mask is used for evaluation in numpy especially
mask = arr % 2 == 0
print(f"Even numebers : {arr[mask]}")

Even numebers : [ 2  4  6  8 10]


### Indexing vs np.where()

In [8]:
indices = [0,2,4]
print(arr[indices])

where_result = np.where(arr > 5)
print(where_result)
print(f"numebers > 5    : {arr[where_result]}")

condition_arr = np.where(arr > 5 , arr * 2 , arr)
print(f"conditioned array = {condition_arr}")

[1 3 5]
(array([5, 6, 7, 8, 9]),)
numebers > 5    : [ 6  7  8  9 10]
conditioned array = [ 1  2  3  4  5 12 14 16 18 20]


### Adding and Removing data

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)

combined_arr = np.concat((arr1 , arr2))
print("combined array = ",combined_arr)

tmp = np.array([
    [1,2],
    [3,4]
])

# adding new row
n_row = np.array([5,6])
print("new array with new row : \n",np.vstack((tmp , n_row)))

# adding new col 
n_col = np.array([
    [5],
    [6]
])
print("new array with new col : \n",np.hstack((tmp , n_col)))


# Deletion
tmp1 = np.array([1,2,3,4,5])
deleted = np.delete(tmp1 , 2)
print(deleted)

[5 7 9]
combined array =  [1 2 3 4 5 6]
new array with new row : 
 [[1 2]
 [3 4]
 [5 6]]
new array with new col : 
 [[1 2 5]
 [3 4 6]]
[1 2 4 5]


In [10]:
# Saving variables
arr = np.array([1,2,3])
np.save("arr.npy" , arr)

# Loading saved data
loaded_arr = np.load("arr.npy")
print(loaded_arr)

[1 2 3]


In [19]:
A = [
    [1,2,3],
    [4,5,6]
]

sum = 0
for i in range(len(A)):
    for j in range(len(A[i])):
        if i == j:  
            print(A[i][j])
print(float(sum))

1
5
0.0
